network:
  server_id: 30
  server_type: 3
  work_thread: 8
  enc_word: 0
  server_host: 10.246.34.84
  front_port: 0
  listens:
    -
      session_type: 3   #监听客户端
      listen_port: 9000
      
    -
      session_type: 1  #监听gate
      listen_port: 8001

lua_path: ./scripts/login/main.lua

cpp_log:
  async: false
  enable_console: true
  name: login_engine
  level: 1